### ISSUE TITLE
Characters are not actually escaped

### ISSUE THREAD

**Issue by Sparika** [scholtzan/rdf-rs#4]
The `RdfSyntaxSpecs::escape_literal` has no actual effect on the litteral being escaped. The function uses https://doc.rust-lang.org/std/string/struct.String.html#method.replace which returns a String but this String is not affected to the `escaped_literal` variable. 

Besides, the related tests are incorrect : 
```rust
        let node = Node::LiteralNode {
            literal: "literal ' \" ".to_string(),
            data_type: None,
            language: None,
        };

        assert_eq!(
            formatter.format_node(&node),
            "\"literal \' \" \"".to_string()
        );
```
As the litteral is enclosed with `"`, `'` and `\'` are equivalent, the test also compares `\"` to `\"`, and it is missing the test for escaping `\` so the test does not demonstrate escaping.

I suggest testing against 
```rust
        assert_eq!(
            formatter.format_node(&node),
            "\"literal \\' \\\\ \\\" \"".to_string()
        );
```

I suggest to replace the use of `RdfSyntaxSpecs::escape_literal` with https://doc.servo.org/std/str/struct.EscapeDefault.html or https://doc.servo.org/std/str/struct.EscapeDebug.html.

**Comment by scholtzan** [comment]
Thanks, just merged the PR.
